name: Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:

  build-ueransim-rock:
    uses: ./.github/workflows/build.yaml
    with:
      artifact-name: ueransim-rock
      path: ueransim

  build-gnbsim-rock:
    uses: ./.github/workflows/build.yaml
    with:
      artifact-name: gnbsim-rock
      path: sdcore-gnbsim

  build-ubuntu-router-rock:
    uses: ./.github/workflows/build.yaml
    with:
      artifact-name: ubuntu-router
      path: ubuntu-router

  publish-ueransim-rock:
    needs: build-ueransim-rock
    if: github.ref_name == 'main'
    uses: ./.github/workflows/publish.yaml
    with:
      artifact-name: ueransim-rock

  publish-gnbsim-rock:
    needs: build-gnbsim-rock
    if: github.ref_name == 'main'
    uses: ./.github/workflows/publish.yaml
    with:
      artifact-name: gnbsim-rock

  publish-ubuntu-router-rock:
    needs: build-ubuntu-router-rock
    if: github.ref_name == 'main'
    uses: ./.github/workflows/publish.yaml
    with:
      artifact-name: ubuntu-router
